# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from lmf_server.models.base_model_ import Model
from lmf_server.models.ciphering_data_set import CipheringDataSet
import re
from lmf_server import util

from lmf_server.models.ciphering_data_set import CipheringDataSet  # noqa: E501
import re  # noqa: E501

class CipheringKeyInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, ciphering_data=None, supported_features=None):  # noqa: E501
        """CipheringKeyInfo - a model defined in OpenAPI

        :param ciphering_data: The ciphering_data of this CipheringKeyInfo.  # noqa: E501
        :type ciphering_data: List[CipheringDataSet]
        :param supported_features: The supported_features of this CipheringKeyInfo.  # noqa: E501
        :type supported_features: str
        """
        self.openapi_types = {
            'ciphering_data': List[CipheringDataSet],
            'supported_features': str
        }

        self.attribute_map = {
            'ciphering_data': 'cipheringData',
            'supported_features': 'supportedFeatures'
        }

        self._ciphering_data = ciphering_data
        self._supported_features = supported_features

    @classmethod
    def from_dict(cls, dikt) -> 'CipheringKeyInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CipheringKeyInfo of this CipheringKeyInfo.  # noqa: E501
        :rtype: CipheringKeyInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ciphering_data(self):
        """Gets the ciphering_data of this CipheringKeyInfo.


        :return: The ciphering_data of this CipheringKeyInfo.
        :rtype: List[CipheringDataSet]
        """
        return self._ciphering_data

    @ciphering_data.setter
    def ciphering_data(self, ciphering_data):
        """Sets the ciphering_data of this CipheringKeyInfo.


        :param ciphering_data: The ciphering_data of this CipheringKeyInfo.
        :type ciphering_data: List[CipheringDataSet]
        """
        if ciphering_data is None:
            raise ValueError("Invalid value for `ciphering_data`, must not be `None`")  # noqa: E501
        if ciphering_data is not None and len(ciphering_data) < 1:
            raise ValueError("Invalid value for `ciphering_data`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._ciphering_data = ciphering_data

    @property
    def supported_features(self):
        """Gets the supported_features of this CipheringKeyInfo.

        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.   # noqa: E501

        :return: The supported_features of this CipheringKeyInfo.
        :rtype: str
        """
        return self._supported_features

    @supported_features.setter
    def supported_features(self, supported_features):
        """Sets the supported_features of this CipheringKeyInfo.

        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.   # noqa: E501

        :param supported_features: The supported_features of this CipheringKeyInfo.
        :type supported_features: str
        """
        if supported_features is not None and not re.search(r'^[A-Fa-f0-9]*$', supported_features):  # noqa: E501
            raise ValueError("Invalid value for `supported_features`, must be a follow pattern or equal to `/^[A-Fa-f0-9]*$/`")  # noqa: E501

        self._supported_features = supported_features
