# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from lmf_server.models.base_model_ import Model
import re
from lmf_server import util

import re  # noqa: E501

class CipherRequestData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, amf_call_back_uri=None, supported_features=None):  # noqa: E501
        """CipherRequestData - a model defined in OpenAPI

        :param amf_call_back_uri: The amf_call_back_uri of this CipherRequestData.  # noqa: E501
        :type amf_call_back_uri: str
        :param supported_features: The supported_features of this CipherRequestData.  # noqa: E501
        :type supported_features: str
        """
        self.openapi_types = {
            'amf_call_back_uri': str,
            'supported_features': str
        }

        self.attribute_map = {
            'amf_call_back_uri': 'amfCallBackURI',
            'supported_features': 'supportedFeatures'
        }

        self._amf_call_back_uri = amf_call_back_uri
        self._supported_features = supported_features

    @classmethod
    def from_dict(cls, dikt) -> 'CipherRequestData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CipherRequestData of this CipherRequestData.  # noqa: E501
        :rtype: CipherRequestData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amf_call_back_uri(self):
        """Gets the amf_call_back_uri of this CipherRequestData.

        String providing an URI formatted according to RFC 3986.  # noqa: E501

        :return: The amf_call_back_uri of this CipherRequestData.
        :rtype: str
        """
        return self._amf_call_back_uri

    @amf_call_back_uri.setter
    def amf_call_back_uri(self, amf_call_back_uri):
        """Sets the amf_call_back_uri of this CipherRequestData.

        String providing an URI formatted according to RFC 3986.  # noqa: E501

        :param amf_call_back_uri: The amf_call_back_uri of this CipherRequestData.
        :type amf_call_back_uri: str
        """
        if amf_call_back_uri is None:
            raise ValueError("Invalid value for `amf_call_back_uri`, must not be `None`")  # noqa: E501

        self._amf_call_back_uri = amf_call_back_uri

    @property
    def supported_features(self):
        """Gets the supported_features of this CipherRequestData.

        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.   # noqa: E501

        :return: The supported_features of this CipherRequestData.
        :rtype: str
        """
        return self._supported_features

    @supported_features.setter
    def supported_features(self, supported_features):
        """Sets the supported_features of this CipherRequestData.

        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.   # noqa: E501

        :param supported_features: The supported_features of this CipherRequestData.
        :type supported_features: str
        """
        #if supported_features is not None and not re.search(r'^[A-Fa-f0-9]*$', supported_features):  # noqa: E501
        #    raise ValueError("Invalid value for `supported_features`, must be a follow pattern or equal to `/^[A-Fa-f0-9]*$/`")  # noqa: E501

        self._supported_features = supported_features
