# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from lmf_server.models.base_model_ import Model
from lmf_server import util


class HorizontalVelocityWithUncertainty(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, h_speed=None, bearing=None, h_uncertainty=None):  # noqa: E501
        """HorizontalVelocityWithUncertainty - a model defined in OpenAPI

        :param h_speed: The h_speed of this HorizontalVelocityWithUncertainty.  # noqa: E501
        :type h_speed: float
        :param bearing: The bearing of this HorizontalVelocityWithUncertainty.  # noqa: E501
        :type bearing: int
        :param h_uncertainty: The h_uncertainty of this HorizontalVelocityWithUncertainty.  # noqa: E501
        :type h_uncertainty: float
        """
        self.openapi_types = {
            'h_speed': float,
            'bearing': int,
            'h_uncertainty': float
        }

        self.attribute_map = {
            'h_speed': 'hSpeed',
            'bearing': 'bearing',
            'h_uncertainty': 'hUncertainty'
        }

        self._h_speed = h_speed
        self._bearing = bearing
        self._h_uncertainty = h_uncertainty

    @classmethod
    def from_dict(cls, dikt) -> 'HorizontalVelocityWithUncertainty':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HorizontalVelocityWithUncertainty of this HorizontalVelocityWithUncertainty.  # noqa: E501
        :rtype: HorizontalVelocityWithUncertainty
        """
        return util.deserialize_model(dikt, cls)

    @property
    def h_speed(self):
        """Gets the h_speed of this HorizontalVelocityWithUncertainty.

        Indicates value of horizontal speed.  # noqa: E501

        :return: The h_speed of this HorizontalVelocityWithUncertainty.
        :rtype: float
        """
        return self._h_speed

    @h_speed.setter
    def h_speed(self, h_speed):
        """Sets the h_speed of this HorizontalVelocityWithUncertainty.

        Indicates value of horizontal speed.  # noqa: E501

        :param h_speed: The h_speed of this HorizontalVelocityWithUncertainty.
        :type h_speed: float
        """
        if h_speed is None:
            raise ValueError("Invalid value for `h_speed`, must not be `None`")  # noqa: E501
        if h_speed is not None and h_speed > 2047:  # noqa: E501
            raise ValueError("Invalid value for `h_speed`, must be a value less than or equal to `2047`")  # noqa: E501
        if h_speed is not None and h_speed < 0:  # noqa: E501
            raise ValueError("Invalid value for `h_speed`, must be a value greater than or equal to `0`")  # noqa: E501

        self._h_speed = h_speed

    @property
    def bearing(self):
        """Gets the bearing of this HorizontalVelocityWithUncertainty.

        Indicates value of angle.  # noqa: E501

        :return: The bearing of this HorizontalVelocityWithUncertainty.
        :rtype: int
        """
        return self._bearing

    @bearing.setter
    def bearing(self, bearing):
        """Sets the bearing of this HorizontalVelocityWithUncertainty.

        Indicates value of angle.  # noqa: E501

        :param bearing: The bearing of this HorizontalVelocityWithUncertainty.
        :type bearing: int
        """
        if bearing is None:
            raise ValueError("Invalid value for `bearing`, must not be `None`")  # noqa: E501
        if bearing is not None and bearing > 360:  # noqa: E501
            raise ValueError("Invalid value for `bearing`, must be a value less than or equal to `360`")  # noqa: E501
        if bearing is not None and bearing < 0:  # noqa: E501
            raise ValueError("Invalid value for `bearing`, must be a value greater than or equal to `0`")  # noqa: E501

        self._bearing = bearing

    @property
    def h_uncertainty(self):
        """Gets the h_uncertainty of this HorizontalVelocityWithUncertainty.

        Indicates value of speed uncertainty.  # noqa: E501

        :return: The h_uncertainty of this HorizontalVelocityWithUncertainty.
        :rtype: float
        """
        return self._h_uncertainty

    @h_uncertainty.setter
    def h_uncertainty(self, h_uncertainty):
        """Sets the h_uncertainty of this HorizontalVelocityWithUncertainty.

        Indicates value of speed uncertainty.  # noqa: E501

        :param h_uncertainty: The h_uncertainty of this HorizontalVelocityWithUncertainty.
        :type h_uncertainty: float
        """
        if h_uncertainty is None:
            raise ValueError("Invalid value for `h_uncertainty`, must not be `None`")  # noqa: E501
        if h_uncertainty is not None and h_uncertainty > 255:  # noqa: E501
            raise ValueError("Invalid value for `h_uncertainty`, must be a value less than or equal to `255`")  # noqa: E501
        if h_uncertainty is not None and h_uncertainty < 0:  # noqa: E501
            raise ValueError("Invalid value for `h_uncertainty`, must be a value greater than or equal to `0`")  # noqa: E501

        self._h_uncertainty = h_uncertainty
