# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from lmf_server.models.base_model_ import Model
from lmf_server.models.local2d_point_uncertainty_ellipse import Local2dPointUncertaintyEllipse
from lmf_server.models.local3d_point_uncertainty_ellipsoid import Local3dPointUncertaintyEllipsoid
from lmf_server.models.local_origin import LocalOrigin
from lmf_server.models.relative_cartesian_location import RelativeCartesianLocation
from lmf_server.models.supported_gad_shapes import SupportedGADShapes
from lmf_server.models.uncertainty_ellipse import UncertaintyEllipse
from lmf_server.models.uncertainty_ellipsoid import UncertaintyEllipsoid
from lmf_server import util

from lmf_server.models.local2d_point_uncertainty_ellipse import Local2dPointUncertaintyEllipse  # noqa: E501
from lmf_server.models.local3d_point_uncertainty_ellipsoid import Local3dPointUncertaintyEllipsoid  # noqa: E501
from lmf_server.models.local_origin import LocalOrigin  # noqa: E501
from lmf_server.models.relative_cartesian_location import RelativeCartesianLocation  # noqa: E501
from lmf_server.models.supported_gad_shapes import SupportedGADShapes  # noqa: E501
from lmf_server.models.uncertainty_ellipse import UncertaintyEllipse  # noqa: E501
from lmf_server.models.uncertainty_ellipsoid import UncertaintyEllipsoid  # noqa: E501

class LocalArea(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, shape=None, local_origin=None, point=None, uncertainty_ellipse=None, confidence=None, uncertainty_ellipsoid=None):  # noqa: E501
        """LocalArea - a model defined in OpenAPI

        :param shape: The shape of this LocalArea.  # noqa: E501
        :type shape: SupportedGADShapes
        :param local_origin: The local_origin of this LocalArea.  # noqa: E501
        :type local_origin: LocalOrigin
        :param point: The point of this LocalArea.  # noqa: E501
        :type point: RelativeCartesianLocation
        :param uncertainty_ellipse: The uncertainty_ellipse of this LocalArea.  # noqa: E501
        :type uncertainty_ellipse: UncertaintyEllipse
        :param confidence: The confidence of this LocalArea.  # noqa: E501
        :type confidence: int
        :param uncertainty_ellipsoid: The uncertainty_ellipsoid of this LocalArea.  # noqa: E501
        :type uncertainty_ellipsoid: UncertaintyEllipsoid
        """
        self.openapi_types = {
            'shape': SupportedGADShapes,
            'local_origin': LocalOrigin,
            'point': RelativeCartesianLocation,
            'uncertainty_ellipse': UncertaintyEllipse,
            'confidence': int,
            'uncertainty_ellipsoid': UncertaintyEllipsoid
        }

        self.attribute_map = {
            'shape': 'shape',
            'local_origin': 'localOrigin',
            'point': 'point',
            'uncertainty_ellipse': 'uncertaintyEllipse',
            'confidence': 'confidence',
            'uncertainty_ellipsoid': 'uncertaintyEllipsoid'
        }

        self._shape = shape
        self._local_origin = local_origin
        self._point = point
        self._uncertainty_ellipse = uncertainty_ellipse
        self._confidence = confidence
        self._uncertainty_ellipsoid = uncertainty_ellipsoid

    @classmethod
    def from_dict(cls, dikt) -> 'LocalArea':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LocalArea of this LocalArea.  # noqa: E501
        :rtype: LocalArea
        """
        return util.deserialize_model(dikt, cls)

    @property
    def shape(self):
        """Gets the shape of this LocalArea.


        :return: The shape of this LocalArea.
        :rtype: SupportedGADShapes
        """
        return self._shape

    @shape.setter
    def shape(self, shape):
        """Sets the shape of this LocalArea.


        :param shape: The shape of this LocalArea.
        :type shape: SupportedGADShapes
        """
        if shape is None:
            raise ValueError("Invalid value for `shape`, must not be `None`")  # noqa: E501

        self._shape = shape

    @property
    def local_origin(self):
        """Gets the local_origin of this LocalArea.


        :return: The local_origin of this LocalArea.
        :rtype: LocalOrigin
        """
        return self._local_origin

    @local_origin.setter
    def local_origin(self, local_origin):
        """Sets the local_origin of this LocalArea.


        :param local_origin: The local_origin of this LocalArea.
        :type local_origin: LocalOrigin
        """
        if local_origin is None:
            raise ValueError("Invalid value for `local_origin`, must not be `None`")  # noqa: E501

        self._local_origin = local_origin

    @property
    def point(self):
        """Gets the point of this LocalArea.


        :return: The point of this LocalArea.
        :rtype: RelativeCartesianLocation
        """
        return self._point

    @point.setter
    def point(self, point):
        """Sets the point of this LocalArea.


        :param point: The point of this LocalArea.
        :type point: RelativeCartesianLocation
        """
        if point is None:
            raise ValueError("Invalid value for `point`, must not be `None`")  # noqa: E501

        self._point = point

    @property
    def uncertainty_ellipse(self):
        """Gets the uncertainty_ellipse of this LocalArea.


        :return: The uncertainty_ellipse of this LocalArea.
        :rtype: UncertaintyEllipse
        """
        return self._uncertainty_ellipse

    @uncertainty_ellipse.setter
    def uncertainty_ellipse(self, uncertainty_ellipse):
        """Sets the uncertainty_ellipse of this LocalArea.


        :param uncertainty_ellipse: The uncertainty_ellipse of this LocalArea.
        :type uncertainty_ellipse: UncertaintyEllipse
        """
        if uncertainty_ellipse is None:
            raise ValueError("Invalid value for `uncertainty_ellipse`, must not be `None`")  # noqa: E501

        self._uncertainty_ellipse = uncertainty_ellipse

    @property
    def confidence(self):
        """Gets the confidence of this LocalArea.

        Indicates value of confidence.  # noqa: E501

        :return: The confidence of this LocalArea.
        :rtype: int
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence):
        """Sets the confidence of this LocalArea.

        Indicates value of confidence.  # noqa: E501

        :param confidence: The confidence of this LocalArea.
        :type confidence: int
        """
        if confidence is None:
            raise ValueError("Invalid value for `confidence`, must not be `None`")  # noqa: E501
        if confidence is not None and confidence > 100:  # noqa: E501
            raise ValueError("Invalid value for `confidence`, must be a value less than or equal to `100`")  # noqa: E501
        if confidence is not None and confidence < 0:  # noqa: E501
            raise ValueError("Invalid value for `confidence`, must be a value greater than or equal to `0`")  # noqa: E501

        self._confidence = confidence

    @property
    def uncertainty_ellipsoid(self):
        """Gets the uncertainty_ellipsoid of this LocalArea.


        :return: The uncertainty_ellipsoid of this LocalArea.
        :rtype: UncertaintyEllipsoid
        """
        return self._uncertainty_ellipsoid

    @uncertainty_ellipsoid.setter
    def uncertainty_ellipsoid(self, uncertainty_ellipsoid):
        """Sets the uncertainty_ellipsoid of this LocalArea.


        :param uncertainty_ellipsoid: The uncertainty_ellipsoid of this LocalArea.
        :type uncertainty_ellipsoid: UncertaintyEllipsoid
        """
        if uncertainty_ellipsoid is None:
            raise ValueError("Invalid value for `uncertainty_ellipsoid`, must not be `None`")  # noqa: E501

        self._uncertainty_ellipsoid = uncertainty_ellipsoid
